



client:
  kakao:
    host: https://dapi.kakao.com
    search-uri: /v2/search/blog
    api-key: 8598e40172eaf4f67dddd54f607a83c6

  naver:
    host: https://openapi.naver.com
    search-uri: /v1/search/blog.json
    client-id: u0DSlBU9FyCRXInyq2k3
    client-secret: hJJcv4J9_I


circuit:
  failure-rate: 4
  wait-duration-in-open-state: 5000 #milli seconds
  timeout-duration-second: 4 #seconds
  sliding-window-size: 2
