server:
  port: 9090


spring:
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  h2:
    console:
      path: /h2
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa

  redis:
    host: localhost
    port: 6379



client:
  kakao:
    host: https://dapi.kakao.com
    search-uri: /v2/search/blog
    api-key: 8598e40172eaf4f67dddd54f607a83c6

  naver:
    host: https://openapi.naver.com
    search-uri: /v1/search/blog.json
    client-id: u0DSlBU9FyCRXInyq2k3
    client-secret: hJJcv4J9_I


infra:
  enable:
    redis: false

